In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import math
import json
from wordcloud import WordCloud, STOPWORDS
import gzip
from pylab import xticks
import tqdm.notebook 
from tqdm.notebook import trange
import pickle
import warnings
warnings.filterwarnings("ignore")
import plotly.express as px

In [24]:

#Importing the data
df_movie_meta = pd.read_table("./data/MovieSummaries/movie.metadata.tsv", header=None)
df_movie_meta.columns=["Wikipedia movie ID", "Freebase movie ID", "Movie name", "Movie release date", 
                     "Movie box office revenue", "Movie runtime", "Movie languages", "Movie countries", "Movie genres"]

In [25]:
df_movie_meta = df_movie_meta.drop(columns = ['Movie countries', 'Movie languages', 'Movie runtime', 'Movie box office revenue', 'Movie name', 'Movie release date'])
df_movie_meta

,Wikipedia movie ID,Freebase movie ID,Movie genres
0,975900,/m/03vyhn,"{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,"{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,"{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,"{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,"{""/m/07s9rl0"": ""Drama""}"
...,...,...,...
81736,35228177,/m/0j7hxnt,"{""/m/07s9rl0"": ""Drama""}"
81737,34980460,/m/0g4pl34,"{""/m/03bxz7"": ""Biographical film"", ""/m/07s9rl0..."
81738,9971909,/m/02pygw1,"{""/m/06nbt"": ""Satire"", ""/m/01z4y"": ""Comedy""}"
81739,913762,/m/03pcrp,"{""/m/06n90"": ""Science Fiction"", ""/m/0gw5n2f"": ..."
81740,12476867,/m/02w7zz8,"{""/m/01jfsb"": ""Thriller"", ""/m/03npn"": ""Horror""..."

In [26]:

#Creating lists in desired columns
# df_movie_meta['Movie countries'] = df_movie_meta['Movie countries'].apply(lambda x: json.loads(x)) # Converts to dictionnary
# df_movie_meta['Movie countries'] = df_movie_meta['Movie countries'].apply(lambda x: list(x.values()))
df_movie_meta['Movie genres'] = df_movie_meta['Movie genres'].apply(lambda x: json.loads(x)) # Converts to dictionnary
df_movie_meta['Movie genres'] = df_movie_meta['Movie genres'].apply(lambda x: list(x.values()))
# df_movie_meta['Movie languages'] = df_movie_meta['Movie languages'].apply(lambda x: json.loads(x)) # Converts to dictionnary
# df_movie_meta['Movie languages'] = df_movie_meta['Movie languages'].apply(lambda x: list(x.values()))

In [27]:
df_movie_meta

,Wikipedia movie ID,Freebase movie ID,Movie genres
0,975900,/m/03vyhn,"[Thriller, Science Fiction, Horror, Adventure,..."
1,3196793,/m/08yl5d,"[Mystery, Biographical film, Drama, Crime Drama]"
2,28463795,/m/0crgdbh,"[Crime Fiction, Drama]"
3,9363483,/m/0285_cd,"[Thriller, Erotic thriller, Psychological thri..."
4,261236,/m/01mrr1,[Drama]
...,...,...,...
81736,35228177,/m/0j7hxnt,[Drama]
81737,34980460,/m/0g4pl34,"[Biographical film, Drama, Documentary]"
81738,9971909,/m/02pygw1,"[Satire, Comedy]"
81739,913762,/m/03pcrp,"[Science Fiction, Japanese Movies, Adventure, ..."
81740,12476867,/m/02w7zz8,"[Thriller, Horror, Slasher, Teen]"

In [31]:
df_movie_meta = df_movie_meta.explode('Movie genres')

In [47]:
s = df_movie_meta['Movie genres'].value_counts()[:30]
s

Drama               34007
Comedy              16349
Romance Film        10234
Black-and-white      9094
Action               8798
Thriller             8744
Short Film           8141
World cinema         7155
Crime Fiction        6948
Indie                6897
Documentary          5630
Horror               5280
Silent film          5250
Adventure            4963
Family Film          4598
Action/Adventure     4561
Comedy film          4362
Musical              4160
Animation            3534
Romantic drama       3372
Mystery              3195
Science Fiction      3052
Fantasy              2820
Romantic comedy      2680
War film             2652
Japanese Movies      2322
Western              2226
Crime Thriller       2122
Period piece         1758
Comedy-drama         1720
Name: Movie genres, dtype: int64

In [52]:
df_popular_genres = df_movie_meta[df_movie_meta.isin(s.index[s >= 4500]).values]

In [53]:
df_popular_genres['Movie genres'].value_counts()

Drama               34007
Comedy              16349
Romance Film        10234
Black-and-white      9094
Action               8798
Thriller             8744
Short Film           8141
World cinema         7155
Crime Fiction        6948
Indie                6897
Documentary          5630
Horror               5280
Silent film          5250
Adventure            4963
Family Film          4598
Action/Adventure     4561
Name: Movie genres, dtype: int64

In [54]:
df_popular_genres.to_pickle('movies_id_frequent_genders.p')

In [ ]:
#df_popular_genres['Movie genres'] = df['Movie genres'].replace({'Action':'action/adventure', 'r':'responsive'})